# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/sda5/s9_pynq/s9_pynq.srcs/sources_1/bd/s9_pynq/ip/s9_pynq_processing_system7_0_0/s9_pynq_processing_system7_0_0.xci
# IP: The module: 's9_pynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/sda5/s9_pynq/s9_pynq.srcs/sources_1/bd/s9_pynq/ip/s9_pynq_processing_system7_0_0/s9_pynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 's9_pynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /mnt/sda5/s9_pynq/s9_pynq.srcs/sources_1/bd/s9_pynq/ip/s9_pynq_processing_system7_0_0/s9_pynq_processing_system7_0_0.xci
# IP: The module: 's9_pynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/sda5/s9_pynq/s9_pynq.srcs/sources_1/bd/s9_pynq/ip/s9_pynq_processing_system7_0_0/s9_pynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 's9_pynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
