# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/s9_pynq/s9_pynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==s9_pynq || ORIG_REF_NAME==s9_pynq} -quiet] -quiet

# IP: bd/s9_pynq/ip/s9_pynq_processing_system7_0_0/s9_pynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==s9_pynq_processing_system7_0_0 || ORIG_REF_NAME==s9_pynq_processing_system7_0_0} -quiet] -quiet

# XDC: bd/s9_pynq/s9_pynq_ooc.xdc
